### PR TITLE
Make rootless operator the default

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We now use the rootless operator the default one. Docs have been updated
as well.
#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
- Make rootless operator deployment the default
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Funny, we cannot apply the default AppArmor profile because this would block the operator init.

**Comment by hasheddan** [comment]
@saschagrunert feel free to lift hold here if ready :)

**Comment by saschagrunert** [comment]
Thanks!

/hold cancel

**Pull request merged**
